/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as PipelinesIdRouteImport } from './routes/pipelines.$id'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIdRoute = PipelinesIdRouteImport.update({
  id: '/pipelines/$id',
  path: '/pipelines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/pipelines/$id': typeof PipelinesIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/pipelines/$id': typeof PipelinesIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/pipelines/$id': typeof PipelinesIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/events' | '/pipelines/$id' | '/runs/$runId' | '/workflows/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/events' | '/pipelines/$id' | '/runs/$runId' | '/workflows/$id'
  id:
    | '__root__'
    | '/'
    | '/api/events'
    | '/pipelines/$id'
    | '/runs/$runId'
    | '/workflows/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEventsRoute: typeof ApiEventsRoute
  PipelinesIdRoute: typeof PipelinesIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  WorkflowsIdRoute: typeof WorkflowsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$id': {
      id: '/pipelines/$id'
      path: '/pipelines/$id'
      fullPath: '/pipelines/$id'
      preLoaderRoute: typeof PipelinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEventsRoute: ApiEventsRoute,
  PipelinesIdRoute: PipelinesIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  WorkflowsIdRoute: WorkflowsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
